# Auto-QA Web Automation System - Test Configuration
# Uses alternative ports to avoid conflicts

networks:
  qa_net:
    driver: bridge

volumes:
  ollama_models:
  postgres_data_qa:
  minio_data:

# Shared DB config
x-db-env: &db-env
  DB_HOST: database
  DB_NAME: qa_results
  DB_USER: qa_user
  DB_PASS: qa_password

services:
  # 1. LLM Server (Ollama)
  ollama:
    image: ollama/ollama
    container_name: qa-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - qa_net
    command: ["serve"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    profiles:
      - ollama

  # 2. Database
  database:
    image: postgres:18-alpine
    container_name: qa-database
    ports:
      - "15433:5432"
    environment:
      POSTGRES_DB: qa_results
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
    volumes:
      - postgres_data_qa:/var/lib/postgresql/data
    networks:
      - qa_net
    restart: always

  # 3. MinIO Object Storage for Screenshots
  minio:
    image: minio/minio:latest
    container_name: qa-minio
    ports:
      - "9004:9000"
      - "9005:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - qa_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # 5. Web UI
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: qa-web
    ports:
      - "3001:80"
    environment:
      PYTHONUNBUFFERED: 1
      PORT: 80
      BRAIN_API_URL: http://brain:9001
      DOCKER_API_VERSION: "1.52"
      <<: *db-env
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: qa-screenshots
      MINIO_SECURE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - qa_net
    depends_on:
      - brain
      - database
    restart: always

  # 6. AI Brain with Multi-Agent System
  brain:
    build:
      context: .
      dockerfile: apps/brain/Dockerfile
    container_name: qa-brain
    ports:
      - "9001:9000"
    environment:
      PYTHONUNBUFFERED: 1
      PORT: 9000
      OLLAMA_API_URL: http://ollama:11434
      EXECUTOR_API_URL: http://executor:9002
      LLM_MODEL: gemma3:1b
      <<: *db-env
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: qa-screenshots
      MINIO_SECURE: "false"
    networks:
      - qa_net
    depends_on:
      executor:
        condition: service_started
      database:
        condition: service_started
    restart: on-failure

  # 7. Web Automation Executor
  executor:
    build:
      context: .
      dockerfile: apps/executor/Dockerfile
    container_name: qa-executor
    ports:
      - "9002:9001"
    environment:
      PYTHONUNBUFFERED: 1
      PORT: 9001
      OLLAMA_API_URL: http://ollama:11434
      LLM_MODEL: gemma3:1b
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: qa-screenshots
      MINIO_SECURE: "false"
    networks:
      - qa_net
    depends_on:
      - minio
    restart: always
    shm_size: '2gb'
